Shop/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth.decorators import login_required


from . import views

urlpatterns = [
   path('home/', views.home, name="home"),
   path('product/<int:id>/', views.product_detail),
   path('search/', views.search),
   path('brand/<str:name>/', views.brand_detail),
   path('product/post/', views.product_create_view),
   path('product/update/<int:pk>/',
         views.product_update_view, name="updateproduct"),
   path('product/delete/', login_required(views.DeleteProduct.as_view()), name="deleteproduct"),
   path('autocomplete/', views.autocomplete, name="autocomplete"),
   
]

app_name = 'Shop'

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from Shop.views import login_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Shop.urls', namespace='Shop')),
    url(r'^/?$', login_view, name='login'),
    url(r'^accounts/login/$', login_view, name='login'),
    url(r'^accounts/logout/$',auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    url(r'^password/reset/$',
                auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
                name='password_reset'),
   url(r'^password/reset/done/$',
                auth_views.PasswordResetDoneView.as_view(template_name='registration/reset_done.html'),
                name='password_reset_done'),
   url(r'^password/reset/complete/$',
                auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_complete.html'),
                name='password_reset_complete'),
   url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset_confirm.html'),
                name='password_reset_confirm'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from ckeditor.fields import RichTextField



class Brand(models.Model):
    Name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.Name


class Product(models.Model):
    title = models.CharField(max_length=100, unique=True)
    price = models.IntegerField(validators=[MinValueValidator(10000)])
    description = RichTextField()
    image = models.ImageField()
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, related_name='sale')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.title

Shop/forms.py
from django import forms
from .models import Product, Brand
from django.contrib.auth.forms import AuthenticationForm
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth import authenticate


class ProductForm(forms.ModelForm):
    #description  = forms.CharField(widget= CKEditorWidget())
    class Meta:
        model = Product
        fields= '__all__'
        
        widgets = {
            'title' : forms.TextInput(attrs={"class": "form-control","placeholder": "Nhập tên sản phẩm", "pattern": ".{8,}"}),
            'price' : forms.NumberInput(attrs={"min": 10000, "class": "form-control"}),
            'description' : forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
            'brand' : forms.Select(attrs={"class": "form-control"}),
            'image' : forms.FileInput(attrs={"id": "imgInp", "name": "imgInp"})
        }
    

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "username"}) ,max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "password"}), required=True)
    remember_me = forms.BooleanField(required=False,widget= forms.CheckboxInput(attrs={"value": "Remember Me"}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user    

Shop/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.db.models import Q
from .models import Brand, Product
from django.contrib import messages
from .forms import ProductForm, LoginForm
from django.contrib.auth import login
from django.views.generic import View
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.auth.decorators import login_required
import requests

# Create your views here.

@login_required
def home(request):
    latest_products_list = Product.objects.all().order_by('-created_at')
    first_product = latest_products_list[0]
    second_product = latest_products_list[1]
    paginator = Paginator(latest_products_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    template = loader.get_template('Shop/home.html')
    context = {
        'page_obj': page_obj,
        'first_product': first_product,
        'second_product': second_product,
    }
    return HttpResponse(template.render(context, request))


@login_required
def product_detail(request, id):
    template = 'Shop/product_detail.html'
    try:
        product = Product.objects.get(id=id)
    except:

        return render(request, template)

    context = {
        'product': product,
    }

    return render(request, template, context)

@login_required
def brand_detail(request, name):
    product = Product.objects.filter(brand__Name=name)

    paginator = Paginator(product, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }
    template = 'Shop/brand_detail.html'

    return render(request, template, context)

@login_required
def search(request):
    if request.method == 'POST':
        srch = request.POST['search']

        if srch:
            match = Product.objects.filter(
                Q(title__icontains=srch)).order_by('-created_at')

            if match:
                return render(request, 'Shop/search.html', {'products_list': match})
            else:
                match = Product.objects.filter(
                    brand__Name=srch).order_by('-created_at')
                if match:
                    return render(request, 'Shop/search.html', {'products_list': match})
                else:
                    messages.error(request, 'no request found')
        else:
            return HttpResponseRedirect('/search')
    return render(request, 'Shop/search.html')

@login_required
def product_create_view(request):
    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/home')
        else:
            return render(request, 'Shop/product_form.html', {'error': "Thông tin sản phẩm không hợp lệ", 'form': form, 
                            'title': "Đăng tải sản phẩm mới", "button": "Đăng sản phẩm"})
    return render(request, 'Shop/product_form.html', {'form': form, 'title': "Đăng tải sản phẩm mới", "button": "Đăng sản phẩm"})

@login_required
def product_update_view(request, pk):
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/home')
        else:
            return render(request, 'Shop/product_form.html', {'error': "Thông tin sản phẩm không hợp lệ", 'form': form, 
                            'title': "Cập nhật thông tin sản phẩm", "button": "Cập nhật"})
    return render(request, 'Shop/product_form.html', {'form': form, 'title': "Cập nhật thông tin sản phẩm", "button": "Cập nhật"})


def autocomplete(request):
    if 'term' in request.GET:
        products_list = Product.objects.filter(title__icontains=request.GET.get('term')).order_by("-created_at")
        brands_list = Brand.objects.filter(Name__icontains=request.GET.get('term'))
        res = list()
        if (brands_list):
            for brand in brands_list:
                p_list = Product.objects.filter(brand=brand).order_by("-created_at")
                for p in p_list:
                    res.append(p.title)
                res.append(brand.Name)
        else:
            for product in products_list:
                res.append(product.title)
        
        return JsonResponse(res, safe=False)    
    return HttpResponseRedirect('/')


class DeleteProduct(View):
    def get(self, request):
        id = request.GET.get('id', None)
        print(id)
        Product.objects.get(id=id).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)


def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect("/home")
    form = LoginForm(request.POST or None)
    error = ""
    if request.POST and form.is_valid():
        user = form.login(request)
        remember_me = form.cleaned_data['remember_me']
        print(remember_me)
        if user:
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            ''' End reCAPTCHA validation '''
            if result['success']:
                login(request, user)
                if remember_me == False:
                    request.session.set_expiry(0)
                return HttpResponseRedirect("/home")
                        
    
    return render(request, 'registration/login.html', {'form': form, 'err': error })

Shop/templates/Shop/base.html
{% load static %}


{% load product_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <title>V-shop</title>

    {% block style %}
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/home"><img src="{% static 'Shop/images/logo/logo.png' %}" width="30"
                    height="30" class="d-inline-block align-top" alt="logo"> V-shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/home">Trang chủ <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sản phẩm
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% show_brands %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/product/post">Đăng bài</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" method="POST" action="/search/">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" name="search" id="search" placeholder="Search"
                        aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <section style="padding: 20px 60px; min-height: 42.5rem;">
        {% block content %}
        {% endblock %}

    </section>

    <div class="pagination" style="margin: 10px 1rem 10px 1rem">
        {% block page %}
        {% endblock %}
    </div>
    <hr style="margin: 2px 1rem 10px 1rem">
    <p style="margin-bottom: 5px; margin-left: 1rem;">Số sản phẩm hiện có: {%total_posts%} </p>
    <footer class="page-footer font-small row" style="
    background-color: #343a40; margin-left: 0px; margin-right: 0px; padding-top: 0; padding-bottom: 0;">
        <div class=" footer-copyright text-left d-flex col-8 align-items-center" style="color: white;">© 2020 Copyright:&nbsp;  
            <a href="https://github.com/AndyT2503" style="color: white;"> github.com/AndyT2503</a>
        </div>
        <div class="text-right col-4" style="color: white; padding-top: 2px; padding-bottom: 2px;">
            <p style="margin-bottom: 2px;">Xin chào, Admin!</p>
            <a href="{% url 'logout' %}" style="color: white;"> Đăng xuất</a>
        </div>

    </footer>


    {% block javascript %}
    {% endblock %}

    <script>
        $(function () {
            $("#search").autocomplete({
                source: '{% url "Shop:autocomplete" %}',
                minLength: 2
            });
        });
    </script>
    <script>
        $(".delete").click(function (e) {
            e.preventDefault();
            let res = confirm("Do you want to delete?");
            id = $(this).prop('name');
            if (res) {
                $.ajax({
                    url: '{% url "Shop:deleteproduct" %}',
                    dataType: 'json',
                    data: {
                        "id": id
                    },
                    success: function (data) {
                        if (data.deleted) {
                            $("#product" + id).remove();
                        }
                    }
                });
            }
        });
    </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

Shop/templates/Shop/brand_detail.html
{% extends "Shop/base.html" %}
{% load product_tags %}


{% block content %}
{% if page_obj %}
{% for product in page_obj %}
{% with link="" %}
{% include "Shop/item.html" %}
{% endwith %}
{% endfor %}
{% else %}
<p>404NotFound: Brand does not exit</p>
{% endif %}
{% endblock %}

{% block page %}
<span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</span>
{% endblock %}

Shop/templates/Shop/function.html
<a style="color: red; margin-right: 10px;" href="" class="delete" name={{product.id}}>Delete</a>
<a style="color: red;" href="/product/update/{{product.id}}">Update</a>


    

Shop/templates/Shop/home.html
{% extends "Shop/base.html" %}
{% load product_tags %}
{% load humanize %}




{% block content %}
{% for product in page_obj %}

{% with link=".." %}
{% include "Shop/item.html" %}
{% endwith %}
{% endfor %}
{% endblock %}



{% block page %}
<span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</span>
{% endblock %}

Shop/templates/Shop/item.html
{% load humanize %}
<div class="media" style="width: 100%; border-radius: 25px; border-color: black; 
border: 2px solid; margin-bottom: 5px; padding: 5px 5px; 
background-color: {% if product == first_product %}
                        aqua
                  {% elif product == second_product %}
                        aquamarine
                  {% else %}
                        white
                  {% endif %};" 
id="product{{product.id}}">
    <img src="{{link}}/media/{{ product.image}} " class="mr-3" width="120" height="120" alt="Sample Image"
        style="margin-top: auto; margin-bottom: auto;">
    <div class="media-body" style="position: relative;">
        <h5 class="mt-0"><a style="color: black; text-decoration: none;"
                href="/product/{{product.id}}">{{ product.title }} <small><i>Ngày đăng:
                        {{ product.created_at }}</i></small></a></h5>
        <p>{{product.description | truncatewords:30 | safe}}</p>
        <p><b>Giá bán: {{product.price | intcomma}} vnđ</b></p>
        <div style="position: absolute; right: 20px; bottom: 0.5px;">
            {% include "Shop/function.html" %}
        </div>
    </div>
</div>

Shop/templates/Shop/product_detail.html
{% extends "Shop/base.html" %}
{% block content %}
{% load humanize %}
{% if product %}
<div class="row">
    <div class="col-8">
        <div class="row" style="padding-left: 10px; margin-bottom: 5px;">
            <small class="col-8">Đăng tải lúc: {{ product.created_at }} </small>
            <small class="col-4">Cập nhật lúc: {{ product.updated_at }}</small>
        </div>
        <div style="height: 38.5rem; border: 1px solid; border-radius: 15px; padding-left: 5px;">
            <h2>{{ product.title }}</h2>
            <p>{{ product.description | safe }}</p>
        </div>
    </div>

    <div class="col-4" style="padding-right: 40px; padding-top: 25px;">
        <img src="../../media/{{ product.image }}" class="img-fluid" alt="">
        <p>
            <center><b>Giá: {{product.price | intcomma}} vnd</b></center>
        </p>
    </div>
</div>
{% else %}
<p>404NotFound: Product does not exit</p>
{% endif %}
{% endblock %}

Shop/templates/Shop/product_form.html
{% extends "Shop/base.html" %}
{% load product_tags %}


{% block style %}
<style>
    .image-preview {
        width: 300px;
        min-height: 350px;
        border: 2px solid #dddddd;
        margin-top: 15px;

        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: bold;
        color: #cccccc;
    }

    .image-preview__image {
        display: none;
    }
</style>
{% endblock %}


{% block content %}
<h5>{{title}}</h5>
<form method="POST" class="row" action="" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group col-7 col-md-7">
        <label for="title"><b>Tên sản phẩm</b></label>
        {{form.title}}
        <label for="price"><b>Giá bán</b></label>
        {{form.price}}
        <div class="form-group">
            <label for="description"><b>Mô tả sản phẩm</b></label>
            {{form.description | safe}}
            {{form.media}}
        </div>
        <div class="form-group">
            <label for="brand"><b>Hãng sản xuất</b></label>
            {{form.brand}}
        </div>
    <button type="submit" class="btn btn-success">{{button}}</button>
    </div>
    <div class="form-group col-5 col-md-5" style="padding-left: 30px;">
        <h6>Hình ảnh sản phẩm</h6>
        {{form.image}}
        <div id="imagePreview" style="margin-top: 15px;">
            <img src="" alt="" class="image-preview__image img-fluid">
        </div>
    </div>
    
</form>
<p style="color: red;">{{error}}</p>
{% endblock %}

{% block javascript %}
<script>
    const inpFile = document.getElementById('imgInp');
    const previewContainer = document.getElementById('imagePreview')
    const previewImage = previewContainer.querySelector(".image-preview__image");

    inpFile.addEventListener("change", function () {
        const file = this.files[0];

        if (file) {
            const reader = new FileReader();
            previewImage.style.display = "block";

            reader.addEventListener("load", function () {
                console.log(this);
                previewImage.setAttribute("src", this.result);
            });

            reader.readAsDataURL(file);
        }
    });

</script>
{% endblock %}

Shop/templates/Shop/search.html
{% extends "Shop/base.html" %}
{% load product_tags %}
{% load humanize %}
{% block content %}
{% if products_list %}
{% for product in products_list %}
{% include "Shop/item.html" %}
{% endfor %}
{% else %}
<p>Không tìm thấy kết quả phù hợp</p>
{% endif %}
{% endblock %}

Shop/templates/Shop/show_brands.html
{% for brand in brand_list %}
<a class="dropdown-item" href="/brand/{{brand.Name}}">{{ brand.Name}}</a>
{% endfor %}